[project]
authors = [{ name = "Klas Åman Norling", email = "klaman-0@student.ltu.se" }]
name = "Cryptography"
version = "0.0.1"
description = "RABE python library that has three schemes, Aw11, KPAc17 and CPAc17"

[dependencies]
rabe = ">=0.1.0"