from typing import Type
from rabe_py import aw11
from rabe_py import ac17
from json import dumps

class ABEscheme:
    def encrypt(self, plaintext:str) -> None:
        pass

    def decrypt(self, ciphertext:str) -> str:
        pass

    def keygen(self) -> None:
        pass
    

class Aw11(ABEscheme):
    """
    Python wrapper for the Aw11 schceme implemented in (rabe::schemes::aw11)
    """
    def __init__(self, attributes:list[str], policy:str):
        self.attributes = attributes
        self.policy = policy 
        self.gk = None
        self.pk = None
        self.msk = None
        self.sk = None

    def encrypt(self, plaintext:str):
        """
        This function encrypts plaintext data using a given JSON string policy and a list of attributes
        and produces a ciphertext if successfull

        Arguments:
        * plaintext - The plaintext data given as a string

        Returns:
        * cipheretext - The ciphertext generated by aw11.encrypt()
        """
        
        ciphertext = aw11.encrypt(self.gk, self.pk, self.policy, plaintext)
        return ciphertext

    

    def decrypt(self, ciphertext):
        """
        This function decrypts the ciphertext if the attributes in msk match the policy of ct.

        Arguments:
        * ciphertext - The ciphertext generated by aw11.encrypt()

        Returns:
        * plaintext - The decrypted ciphertext as a list of u8's, generated by aw11.decrypt()
        """
        
        plaintext = aw11.decrypt(self.gk, self.sk, ciphertext)
        return plaintext


    def generate_static_keys(self):
        """
        This function generates a static key, the global key (gk).
        """
        self.gk = aw11.setup()
    

    def load_static_keys(self, gk):
        """
        This function loads a new static key.

        Arguments:
        * gk - A Global Parameters Key, generated by aw11.setup()
        """
        self.gk = gk


    def keygen(self, user_name:str, user_attribute:list[str]):
        """
        This function generates all non-static keys, public key(pk), master secret key(msk) and a secret key(sk).

        Arguments:
        * user_name       - The name of the user the key is associated with, must be unique
        * user_attributes - A list of string attributes assigned to this user
        """
        
        (pk, msk) = aw11.authgen(self.gk, self.attributes)
        sk = aw11.keygen(self.gk, msk, user_name, user_attribute)
        self.pk = pk
        self.sk = sk
        
        

class KPAc17(ABEscheme):
    """
    Python wrapper for the KPAc17 schceme implemented in (rabe::schemes::ac17)
    """
    def __init__(self, attributes:list[str], policy:str):
        self.attributes = attributes
        self.policy = policy
        self.pk = None
        self.msk = None
        self.sk = None

    def encrypt(self, plaintext:str):
        """
        This function encrypts plaintext data using a given JSON string policy and a list of attributes
        and produces a ciphertext if successfull

        Arguments:
        * plaintext - The plaintext data given as a string

        Returns:
        * cipheretext - The ciphertext generated by ac17.kp_encrypt()
        """
        
        ciphertext = ac17.kp_encrypt(self.pk, self.attributes, plaintext)
        return ciphertext
        

    def decrypt(self, ciphertext:str):
        """
        This function decrypts the ciphertext if the attributes in msk match the policy of ct.

        Arguments:
        * ciphertext - The ciphertext generated by ac17.kp_encrypt()

        Returns:
        * plaintext - The decrypted ciphertext as a list of u8's, generated by ac17.kp_decrypt()
        """
        
        plaintext = ac17.kp_decrypt(self.sk, ciphertext)
        return plaintext
        
    

    def generate_static_keys(self):
        """
        This function generates static keys, the public key (pk) and the master secret key (msk).
        """
        (pk, msk) = ac17.setup()
        self.pk = pk
        self.msk = msk
    

    def load_static_keys(self, pk, msk):
        """
        This function loads new static keys.

        Arguments:
        * pk  - A Public Key, generated by ac17.setup()
        * msk - A Master Secret Key, generated by ac17.setup()
        """
        self.pk = pk
        self.msk = msk


    def keygen(self):
        """
        This function generates the non-static key, secret key(sk)
        """
        self.sk = ac17.kp_keygen(self.msk, self.policy)
    
    

class CPAc17(ABEscheme):
    """
    Python wrapper for the CPAc17 schceme implemented in (rabe::schemes::ac17)
    """
    def __init__(self, attributes:list[str], policy:str):
        self.attributes = attributes
        self.policy = policy
        self.pk = None
        self.msk = None
        self.sk = None
    

    def encrypt(self, plaintext:str):
        """
        This function encrypts plaintext data using a given JSON string policy and a list of attributes
        and produces a ciphertext if successfull

        Arguments:
        * plaintext - The plaintext data given as a string

        Returns:
        * cipheretext - The ciphertext generated by ac17.cp_encrypt()
        """
        ciphertext = ac17.cp_encrypt(self.pk, self.policy, plaintext)
        return ciphertext


    def decrypt(self, ciphertext:str):
        """
        This function decrypts the ciphertext if the attributes in msk match the policy of ct.

        Arguments:
        * ciphertext - The ciphertext generated by ac17.kp_encrypt()

        Returns:
        * plaintext - The decrypted ciphertext as a list of u8's, generated by ac17.cp_decrypt()
        """
 
        plaintext = ac17.cp_decrypt(self.sk, ciphertext)
        return plaintext



    def generate_static_keys(self):
        """
        This function generates static keys, the public key (pk) and the master secret key (msk).
        """
        (pk, msk) = ac17.setup()
        self.pk = pk
        self.msk = msk


    def load_static_keys(self, pk, msk):
        """
        This function loads new static keys.

        Arguments:
        * pk  - A Public Key, generated by ac17.setup()
        * msk - A Master Secret Key, generated by ac17.setup()
        """
        self.pk = pk
        self.msk = msk


    def keygen(self):
        """
        This function generates the non-static key, secret key(sk)
        """
        
        self.sk = ac17.cp_keygen(self.msk, self.attributes)
        


class ABE:
    valid_types: list[Type] = [Aw11, KPAc17, CPAc17]
    # This is run before init and expects a return value
    def __new__(self: "ABE", scheme: Type, attributes: list[str] = None, policy: str = None):
        if scheme not in self.valid_types:
            raise Exception(ValueError("No such scheme"))
        return scheme(attributes, policy)



